task: Task02_Heart
seed: 22

data:
  data_root: /root/workspace/MixConv/data_raw/Task02_Heart
  dataset_info: /root/workspace/MixConv/preprocess_result/Task02_Heart/dataset_summary.pkl
  patch_size: [192, 192, 80] #[160, 160, 80]
  patch_overlap: [0, 0, 0] # [160, 160, 80]
  color_channels: 1
  num_classes: 1
  sample_csv_root: '/root/workspace/MixConv/preprocess_result/Task02_Heart'
  normalization: 'znorm'
  spacing: [1.25, 1.25, 1.37]
  # sample_csv_root: 'datasets/20200818'


train:
  batch_size: 2
  samples_per_volume: 8
  num_workers: 3
  num_iterations: 100
  trans: ['affine', 'noise', 'blur']

eval:
  batch_size: 6
  num_workers: 2
  trans: []

logging:
  use_logging: true
  ckpt_path: ckpts
  use_tensorboard: False
  run_path: runs

optim:
  num_epochs: 100
  # support optim method: [sgd, adam]
  optim_method: adam  #adam
  sgd:
    base_lr: 1e-2
    momentum: 0.9
    weight_decay: 1e-4
    nesterov: false
  adam:
    base_lr: 1e-3
    betas: [0.9, 0.999]
    weight_decay: 0
    amsgrad: false
  use_lr_decay: true
  early_stop:
    use: false
    patience: 5
  # support lr_decay method: [cosine]
  lr_decay_method: poly
  poly:
      exponent: 0.9

criterion:
  # support criterion method: [ExtraCEDiceLoss, cross_entropy_loss, ce_dice_loss, dice_loss]
  criterions: ['BCELoss', 'dice',] #ce_dice_loss
  criterion_coefs: [1.0, 1.0,]

network:
  model_name: model
  is2dPhase: false
  norm_parm:
    norm_type: batch # batch, instance
    num_groups: 8

  block: VGGBlock #MixResBlock # ResBlock #VGGBlock # ResBlock MixResBlock
  base_filters: 32 # number of first filters
  conv_type: Conv3d #MixConvV3 #Conv3d #MixConvV2
  use_pretrained: false
  deep_supervision: false
  load_pretrained: false
  pretrained_path: /root/workspace/MixConv/ckpts/Task02_Heart/MixUNet3D/2021Nov05-133551

  stack: true
  drop: false
  depth: 3




