task: Task30_SLiver07
seed: 22

data:
  data_root: /root/workspace/MixConv/preprocess_result/Task30_SLiver07
  dataset_info: /root/workspace/MixConv/preprocess_result/Task30_SLiver07/dataset_summary.pkl
  patch_size: [192, 192, 7] #[160, 160, 80]
  patch_overlap: [0, 0, 0] # [160, 160, 80]
  color_channels: 1
  num_classes: 1
  sample_csv_root: '/root/workspace/MixConv/preprocess_result/Task30_SLiver07'
  normalization: 'nnorm'
  spacing: [0.7, 0.7, 1.0]
  # sample_csv_root: 'datasets/20200818'


train:
  batch_size: 16
  trans: ['affine', 'noise', 'blur']
  samples_per_volume: 64
  num_workers: 3
  num_iterations: 100

eval:
  batch_size: 48
  num_workers: 2
  trans: []

logging:
  use_logging: true
  ckpt_path: ckpts
  use_tensorboard: False
  run_path: runs

optim:
  num_epochs: 100
  # support optim method: [sgd, adam]
  optim_method: adam  #adam
  sgd:
    base_lr: 1e-2
    momentum: 0.9
    weight_decay: 1e-4
    nesterov: false
  adam:
    base_lr: 1e-3
    betas: [0.9, 0.999]
    weight_decay: 0
    amsgrad: false
  use_lr_decay: true
  early_stop:
    use: false
    patience: 5
  # support lr_decay method: [cosine]
  lr_decay_method: poly
  poly:
      exponent: 0.9

criterion:
  # support criterion method: [ExtraCEDiceLoss, cross_entropy_loss, ce_dice_loss, dice_loss]
  criterions: ['BCELoss', 'dice',] #ce_dice_loss
  criterion_coefs: [1.0, 1.0,]

network:
  model_name: model
  is2dPhase: True
  norm_parm:
    norm_type: instance # group # batch, instance
    num_groups: 32

  block: ResBlock #ResBlock #MixResBlock # ResBlock #VGGBlock # ResBlock MixResBlock
  base_filters: 32 # number of first filters
  conv_type: Conv2d #MixConvV3 #Conv3d #MixConvV2
  deep_supervision: True
  load_pretrained: false
  pretrained_path: /root/workspace/DeepCAD/seg-new/ckpts/UNet3D/2021Nov11-023738

  stack: true
  drop: false
  depth: 3




